version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/locateMe"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
        - "@angular/*"
        - "@angular-devkit/*"
        update-types:
        - "minor"
        - "patch"
      angular-eslint:
        patterns:
        - "@angular-eslint/*"
        update-types:
        - "minor"
        - "patch"
      primeng:
        patterns:
        - "primeng"
        - "@primeng/themes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
